# infrastructure/chaos/node-failure.yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: bot-node-failure
  namespace: production
  labels:
    app: bot
    chaos/type: node-failure
spec:
  action: pod-failure  # Заблокировать пода
  mode: one            # Выбрать 1 под
  duration: 5m         # Длительность теста
  selector:
    namespaces:
      - production     # Namespace приложения
    labelSelectors:
      "app.kubernetes.io/name": "bot"  # Совпадает с лейблами деплоймента