# infrastructure/k8s/postgres-shards.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-shard
spec:
  serviceName: postgres-shard
  replicas: 4
  template:
    spec:
      containers:
      - name: postgres
        image: citusdata/citus:11.2
        env:
        - name: POSTGRES_DB
          value: orders
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: securepass